-- MySQL Script generated by MySQL Workbench
-- Fri Oct 17 14:22:24 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema redbelt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema redbelt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `redbelt` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `redbelt` ;

-- -----------------------------------------------------
-- Table `redbelt`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redbelt`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `alias` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `date_of_birth` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redbelt`.`pokes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redbelt`.`pokes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `poker` VARCHAR(255) NULL,
  `pokee` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redbelt`.`users_has_pokes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redbelt`.`users_has_pokes` (
  `users_id` INT NOT NULL,
  `pokes_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `pokes_id`),
  INDEX `fk_users_has_pokes_pokes1_idx` (`pokes_id` ASC),
  INDEX `fk_users_has_pokes_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_pokes_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `redbelt`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_pokes_pokes1`
    FOREIGN KEY (`pokes_id`)
    REFERENCES `redbelt`.`pokes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
